/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as AppDailyLogRouteImport } from './routes/app/daily-log'
import { Route as AppAdminRouteRouteImport } from './routes/app/admin/route'
import { Route as AppReportsIndexRouteImport } from './routes/app/reports/index'
import { Route as AppQueueIndexRouteImport } from './routes/app/queue/index'
import { Route as AppProjectsIndexRouteImport } from './routes/app/projects/index'
import { Route as AppLabIndexRouteImport } from './routes/app/lab/index'
import { Route as AppClientIndexRouteImport } from './routes/app/client/index'
import { Route as AppAdminIndexRouteImport } from './routes/app/admin/index'
import { Route as AppReportsReportIdRouteImport } from './routes/app/reports/$reportId'
import { Route as AppProjectsProjectIdRouteImport } from './routes/app/projects/$projectId'
import { Route as AppAdminUsersRouteImport } from './routes/app/admin/users'
import { Route as AppAdminSettingsRouteImport } from './routes/app/admin/settings'
import { Route as AppAdminProjectsRouteImport } from './routes/app/admin/projects'
import { Route as AppAdminProctorsRouteImport } from './routes/app/admin/proctors'
import { Route as AppAdminEquipmentRouteImport } from './routes/app/admin/equipment'
import { Route as AppAdminClientsRouteImport } from './routes/app/admin/clients'
import { Route as AppAdminCertificationsRouteImport } from './routes/app/admin/certifications'
import { Route as AppReportsNewKindRouteImport } from './routes/app/reports/new.$kind'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDailyLogRoute = AppDailyLogRouteImport.update({
  id: '/daily-log',
  path: '/daily-log',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminRouteRoute = AppAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppQueueIndexRoute = AppQueueIndexRouteImport.update({
  id: '/queue/',
  path: '/queue/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLabIndexRoute = AppLabIndexRouteImport.update({
  id: '/lab/',
  path: '/lab/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClientIndexRoute = AppClientIndexRouteImport.update({
  id: '/client/',
  path: '/client/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppReportsReportIdRoute = AppReportsReportIdRouteImport.update({
  id: '/reports/$reportId',
  path: '/reports/$reportId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminProjectsRoute = AppAdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminProctorsRoute = AppAdminProctorsRouteImport.update({
  id: '/proctors',
  path: '/proctors',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminEquipmentRoute = AppAdminEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminClientsRoute = AppAdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminCertificationsRoute = AppAdminCertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppReportsNewKindRoute = AppReportsNewKindRouteImport.update({
  id: '/reports/new/$kind',
  path: '/reports/new/$kind',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/app/admin': typeof AppAdminRouteRouteWithChildren
  '/app/daily-log': typeof AppDailyLogRoute
  '/r/$token': typeof RTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/certifications': typeof AppAdminCertificationsRoute
  '/app/admin/clients': typeof AppAdminClientsRoute
  '/app/admin/equipment': typeof AppAdminEquipmentRoute
  '/app/admin/proctors': typeof AppAdminProctorsRoute
  '/app/admin/projects': typeof AppAdminProjectsRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/reports/$reportId': typeof AppReportsReportIdRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/client/': typeof AppClientIndexRoute
  '/app/lab/': typeof AppLabIndexRoute
  '/app/projects/': typeof AppProjectsIndexRoute
  '/app/queue/': typeof AppQueueIndexRoute
  '/app/reports/': typeof AppReportsIndexRoute
  '/app/reports/new/$kind': typeof AppReportsNewKindRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/app/daily-log': typeof AppDailyLogRoute
  '/r/$token': typeof RTokenRoute
  '/app': typeof AppIndexRoute
  '/app/admin/certifications': typeof AppAdminCertificationsRoute
  '/app/admin/clients': typeof AppAdminClientsRoute
  '/app/admin/equipment': typeof AppAdminEquipmentRoute
  '/app/admin/proctors': typeof AppAdminProctorsRoute
  '/app/admin/projects': typeof AppAdminProjectsRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/reports/$reportId': typeof AppReportsReportIdRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/client': typeof AppClientIndexRoute
  '/app/lab': typeof AppLabIndexRoute
  '/app/projects': typeof AppProjectsIndexRoute
  '/app/queue': typeof AppQueueIndexRoute
  '/app/reports': typeof AppReportsIndexRoute
  '/app/reports/new/$kind': typeof AppReportsNewKindRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/app/admin': typeof AppAdminRouteRouteWithChildren
  '/app/daily-log': typeof AppDailyLogRoute
  '/r/$token': typeof RTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/certifications': typeof AppAdminCertificationsRoute
  '/app/admin/clients': typeof AppAdminClientsRoute
  '/app/admin/equipment': typeof AppAdminEquipmentRoute
  '/app/admin/proctors': typeof AppAdminProctorsRoute
  '/app/admin/projects': typeof AppAdminProjectsRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/reports/$reportId': typeof AppReportsReportIdRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/client/': typeof AppClientIndexRoute
  '/app/lab/': typeof AppLabIndexRoute
  '/app/projects/': typeof AppProjectsIndexRoute
  '/app/queue/': typeof AppQueueIndexRoute
  '/app/reports/': typeof AppReportsIndexRoute
  '/app/reports/new/$kind': typeof AppReportsNewKindRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/sign-in'
    | '/app/admin'
    | '/app/daily-log'
    | '/r/$token'
    | '/app/'
    | '/app/admin/certifications'
    | '/app/admin/clients'
    | '/app/admin/equipment'
    | '/app/admin/proctors'
    | '/app/admin/projects'
    | '/app/admin/settings'
    | '/app/admin/users'
    | '/app/projects/$projectId'
    | '/app/reports/$reportId'
    | '/app/admin/'
    | '/app/client/'
    | '/app/lab/'
    | '/app/projects/'
    | '/app/queue/'
    | '/app/reports/'
    | '/app/reports/new/$kind'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/app/daily-log'
    | '/r/$token'
    | '/app'
    | '/app/admin/certifications'
    | '/app/admin/clients'
    | '/app/admin/equipment'
    | '/app/admin/proctors'
    | '/app/admin/projects'
    | '/app/admin/settings'
    | '/app/admin/users'
    | '/app/projects/$projectId'
    | '/app/reports/$reportId'
    | '/app/admin'
    | '/app/client'
    | '/app/lab'
    | '/app/projects'
    | '/app/queue'
    | '/app/reports'
    | '/app/reports/new/$kind'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/sign-in'
    | '/app/admin'
    | '/app/daily-log'
    | '/r/$token'
    | '/app/'
    | '/app/admin/certifications'
    | '/app/admin/clients'
    | '/app/admin/equipment'
    | '/app/admin/proctors'
    | '/app/admin/projects'
    | '/app/admin/settings'
    | '/app/admin/users'
    | '/app/projects/$projectId'
    | '/app/reports/$reportId'
    | '/app/admin/'
    | '/app/client/'
    | '/app/lab/'
    | '/app/projects/'
    | '/app/queue/'
    | '/app/reports/'
    | '/app/reports/new/$kind'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  SignInRoute: typeof SignInRoute
  RTokenRoute: typeof RTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/daily-log': {
      id: '/app/daily-log'
      path: '/daily-log'
      fullPath: '/app/daily-log'
      preLoaderRoute: typeof AppDailyLogRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/reports/': {
      id: '/app/reports/'
      path: '/reports'
      fullPath: '/app/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/queue/': {
      id: '/app/queue/'
      path: '/queue'
      fullPath: '/app/queue/'
      preLoaderRoute: typeof AppQueueIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/projects/': {
      id: '/app/projects/'
      path: '/projects'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/lab/': {
      id: '/app/lab/'
      path: '/lab'
      fullPath: '/app/lab/'
      preLoaderRoute: typeof AppLabIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/client/': {
      id: '/app/client/'
      path: '/client'
      fullPath: '/app/client/'
      preLoaderRoute: typeof AppClientIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/reports/$reportId': {
      id: '/app/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/app/reports/$reportId'
      preLoaderRoute: typeof AppReportsReportIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/projects/$projectId': {
      id: '/app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/app/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/settings': {
      id: '/app/admin/settings'
      path: '/settings'
      fullPath: '/app/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/projects': {
      id: '/app/admin/projects'
      path: '/projects'
      fullPath: '/app/admin/projects'
      preLoaderRoute: typeof AppAdminProjectsRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/proctors': {
      id: '/app/admin/proctors'
      path: '/proctors'
      fullPath: '/app/admin/proctors'
      preLoaderRoute: typeof AppAdminProctorsRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/equipment': {
      id: '/app/admin/equipment'
      path: '/equipment'
      fullPath: '/app/admin/equipment'
      preLoaderRoute: typeof AppAdminEquipmentRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/clients': {
      id: '/app/admin/clients'
      path: '/clients'
      fullPath: '/app/admin/clients'
      preLoaderRoute: typeof AppAdminClientsRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/certifications': {
      id: '/app/admin/certifications'
      path: '/certifications'
      fullPath: '/app/admin/certifications'
      preLoaderRoute: typeof AppAdminCertificationsRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/reports/new/$kind': {
      id: '/app/reports/new/$kind'
      path: '/reports/new/$kind'
      fullPath: '/app/reports/new/$kind'
      preLoaderRoute: typeof AppReportsNewKindRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppAdminRouteRouteChildren {
  AppAdminCertificationsRoute: typeof AppAdminCertificationsRoute
  AppAdminClientsRoute: typeof AppAdminClientsRoute
  AppAdminEquipmentRoute: typeof AppAdminEquipmentRoute
  AppAdminProctorsRoute: typeof AppAdminProctorsRoute
  AppAdminProjectsRoute: typeof AppAdminProjectsRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteRouteChildren: AppAdminRouteRouteChildren = {
  AppAdminCertificationsRoute: AppAdminCertificationsRoute,
  AppAdminClientsRoute: AppAdminClientsRoute,
  AppAdminEquipmentRoute: AppAdminEquipmentRoute,
  AppAdminProctorsRoute: AppAdminProctorsRoute,
  AppAdminProjectsRoute: AppAdminProjectsRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteRouteWithChildren = AppAdminRouteRoute._addFileChildren(
  AppAdminRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppAdminRouteRoute: typeof AppAdminRouteRouteWithChildren
  AppDailyLogRoute: typeof AppDailyLogRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppReportsReportIdRoute: typeof AppReportsReportIdRoute
  AppClientIndexRoute: typeof AppClientIndexRoute
  AppLabIndexRoute: typeof AppLabIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppQueueIndexRoute: typeof AppQueueIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppReportsNewKindRoute: typeof AppReportsNewKindRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminRouteRoute: AppAdminRouteRouteWithChildren,
  AppDailyLogRoute: AppDailyLogRoute,
  AppIndexRoute: AppIndexRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppReportsReportIdRoute: AppReportsReportIdRoute,
  AppClientIndexRoute: AppClientIndexRoute,
  AppLabIndexRoute: AppLabIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppQueueIndexRoute: AppQueueIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppReportsNewKindRoute: AppReportsNewKindRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  SignInRoute: SignInRoute,
  RTokenRoute: RTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
